[build]
  command = "make deploy-preview"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.91.1"

[context.production]
  command = "make all"

[context.docs-development]
  command = "make all-dev"

[context.docs-staging]
  command = "make all-staging"

[context.deploy-preview]
  command = "make deploy-preview"

[context.branch-deploy]
  command = "make deploy-preview"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://docs.nginx.com"

[[redirects]]
  from = "/"
  to = "/nginx-agent/"
  status = 301
  force = true

[[redirects]]
  from = "/nginx-agent/*"
  to = "/404.html"
  status = 404

[[redirects]]
  from = "/nginx-agent/robots.txt"
  to = "https://docs.nginx.com/robots.txt"
  status = 301
  force = true
