version: 2
updates:
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 5
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      # for example, `dependabot-npm_and_yarn-next_js-acorn-6.4.1`
      separator: "-"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    pull-request-branch-name:
      # Separate sections of the branch name with a hyphen
      # for example, `dependabot-npm_and_yarn-next_js-acorn-6.4.1`
      separator: "-"
